Use 'compact' on 'Socket.getifaddrs.map'
In certain situations, when a TUN device is present (e.g., when a VPN
is connected), `Socket.getifaddrs.map(&:addr)` can contain one or more
`nil` elements.  This can lead to errors like the following:

(irb):6:in `select': undefined method `ipv4?' for nil:NilClass (NoMethodError)
        from (irb):6:in `<main>'
        from /usr/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
        from /usr/bin/irb3.0:23:in `load'
        from /usr/bin/irb3.0:23:in `<main>'

This commit prevents such errors by using `compact` to remove any
`nil` elements from the map before passing it to `select`.

Signed-off-by: Sergio Durigan Junior <sergiodj@sergiodj.net>