Make clonefile optional
clonefile fails to build on Netlify:

    clonefile.c:47:58: error: ‘FICLONE’ undeclared

… which is unexpected, but because this is a regression, Nanoc can now work without clonefile as well (and only making use of it when it’s available).